language: node_js
node_js: lts/*
os:
  - linux
env:
  - NODE_ENV=test
install:
  - rm -rf public src package.json package-lock.json
services:
  - redis-server
jobs:
  include:
    - stage: Deploy
      script:
        - './scripts/build.sh'
      deploy:
        provider: heroku
        api_key:
          secure: f+c75gKpcK/8nuJP7tAy0A5ZlubTIOJlNcVasBo6Km7Oqss++DYQhPP06SukgPCGX3R8TDITK9yASceI5R5JfvT069g29+PEcA99PUbKYm17IVqBQyiM1n3vtZkggRijVlStgNe1/898EBIllmE8oFwrJaAn+XiJ7UlEzCYwskS+FrBT3ddm4+kWrZ1or8DC16ZPuVbnYInwS/omeTxujKU52eA3zG/bzMeVVB7ITx95TbzldQs8Y7Z+7C+mWpFeX5FMV9hibgNQuzRs4OrDVgljQFVC4VNtKnb7ylK2epW764X8uSUIic/wA/KdiJ8rk6KD/rveshL/Lc4CcRN3NyHayxPtvdcVdgwwll2Uuo/FEBgU2proIZeZbeF3HlH/iM4N+1yBeP2Fi3k3EYOdvWJonkZ8NxYF2Vdikz2iWFzP3J5TUEzCTqqvmNViUZ0sLY3sStZfXz3KZTMO2G5QTTjpI4FBtIB3NVVWBlIplP39OA/b6TCwrKgJY772BGEb0v3ewCPgRgi1Hb/Wj/TqGGBLPn4M9XEt0mwtx5jXIHJQIRJQYwODdGn4A0SuGv2bIMmDqaNwe4VW3iyk4qJ1ZNVtk4y9NkxNC/0MDS64G96do+wqI5nkZm/DaHcqJcJlyDrDka3LHyG46NOcMdPuhNzsMuvCtpFJa5AKFrK8NSQ=
        skip_cleanup: true
        app: my-pinterest-react
        run: restart
