language: node_js
node_js: lts/*
os:
  - linux
env:
  - NODE_ENV=test
install:
  - rm -rf public src package.json package-lock.json
services:
  - redis-server
jobs:
  include:
    - stage: Deploy
      script:
        - './scripts/build.sh'
      deploy:
        provider: heroku
        api_key:
          secure: rRVQOzJTzPB0N4bGcYzpuy+euC/ubx4p9XVjXHkI4e14Y4BLaCv9o+O9G9LRkZxECPVvK1RwnyJ+H6X3N/Ec+Uft16lYrSwiNMXj7cuJZr00+AkkhcSD8Nyjz0lzO0RLcbwsHnVv+VjYwCgaUEap66kZidIediVWrybhILjTkhaCuPdeRprXfmZw8f7SXEtpuxEm1f0l4AIzRQ5eTCXLw2DJ/0LqWmsYlrlQtPAK57wcnxjwRuFHlBiGbwd10iS9EgAudXGHkDU+0JiLOvXlsNhUrm3a6AiHEyQsJ6sQuPCYqGY3ImCV94UDJTDI3e9YFM6cySs8kNVMhLjUfXZglIh5Ms7r2nif3Vak1SDTf01pDaCdVVV2A1KOSmE0zhpLM5j2YNjUtVnn/F+PFoljfmf/VDhKGAuxbByIjuTzysK5/uA1/Iqmkfyf6nolnStPeEthq2NoTXRIAncDc4NbgBgDAvpdBb65r+FtL8iXS4QpXb2HK+iCyV+A07NbHwB77nxZ3I4n7DX7/Vny9o9vH30m6fJxAUpNwKms/KSI5545nybFyc3EyxS/cg1CLbfVbezIV6qJ55X3aOPe1GaygMdIYxz/DwH7/iY4VoTB3JEhzV3tsjo6yEx0BIXuSjyAVG9hQ0jPXm+T18HilCkJr/omAJB1qUL5foY6cJyD1Ts=
        skip_cleanup: true
        app: my-pinterest-react
        run: restart
